[build]
builder = "RAILPACK"
watchPatterns = ["/backend/**"]

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Initialize database tables before starting the app
[[deploy.preDeployCommands]]
command = "python init_db.py"
