"""Add keywords table for keyword extraction

Revision ID: 5827486fadda
Revises: dd9cb6ba2432
Create Date: 2025-11-06 20:21:35.739751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5827486fadda'
down_revision: Union[str, None] = 'dd9cb6ba2432'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_keywords_article', 'keywords', ['article_id', sa.text('score DESC')], unique=False)
    op.create_index('idx_keywords_created_at', 'keywords', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_keywords_keyword', 'keywords', ['keyword', sa.text('score DESC')], unique=False)
    op.create_index('idx_keywords_score', 'keywords', [sa.text('score DESC')], unique=False)
    op.create_index(op.f('ix_keywords_article_id'), 'keywords', ['article_id'], unique=False)
    op.create_index(op.f('ix_keywords_id'), 'keywords', ['id'], unique=False)
    op.create_index(op.f('ix_keywords_keyword'), 'keywords', ['keyword'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keywords_keyword'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_id'), table_name='keywords')
    op.drop_index(op.f('ix_keywords_article_id'), table_name='keywords')
    op.drop_index('idx_keywords_score', table_name='keywords')
    op.drop_index('idx_keywords_keyword', table_name='keywords')
    op.drop_index('idx_keywords_created_at', table_name='keywords')
    op.drop_index('idx_keywords_article', table_name='keywords')
    op.drop_table('keywords')
    # ### end Alembic commands ###
