"""Add visits table for analytics tracking

Revision ID: 780069fe2ddc
Revises: 403bed34a971
Create Date: 2025-11-03 20:52:18.058024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780069fe2ddc'
down_revision: Union[str, None] = '403bed34a971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visit_id', sa.String(), nullable=False),
    sa.Column('page_url', sa.String(length=500), nullable=False),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('visited_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visits_id'), 'visits', ['id'], unique=False)
    op.create_index(op.f('ix_visits_ip_address'), 'visits', ['ip_address'], unique=False)
    op.create_index(op.f('ix_visits_page_url'), 'visits', ['page_url'], unique=False)
    op.create_index(op.f('ix_visits_referrer'), 'visits', ['referrer'], unique=False)
    op.create_index(op.f('ix_visits_visit_id'), 'visits', ['visit_id'], unique=True)
    op.create_index(op.f('ix_visits_visited_at'), 'visits', ['visited_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_visited_at'), table_name='visits')
    op.drop_index(op.f('ix_visits_visit_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_referrer'), table_name='visits')
    op.drop_index(op.f('ix_visits_page_url'), table_name='visits')
    op.drop_index(op.f('ix_visits_ip_address'), table_name='visits')
    op.drop_index(op.f('ix_visits_id'), table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###
