"""Add entities table for NER

Revision ID: dd9cb6ba2432
Revises: 4f7a36a8402d
Create Date: 2025-11-06 20:07:23.936287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd9cb6ba2432'
down_revision: Union[str, None] = '4f7a36a8402d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('entity_text', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entities_article_type', 'entities', ['article_id', 'entity_type'], unique=False)
    op.create_index('idx_entities_created_at', 'entities', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_entities_text_type', 'entities', ['entity_text', 'entity_type'], unique=False)
    op.create_index(op.f('ix_entities_article_id'), 'entities', ['article_id'], unique=False)
    op.create_index(op.f('ix_entities_entity_text'), 'entities', ['entity_text'], unique=False)
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_id'), 'entities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entities_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_text'), table_name='entities')
    op.drop_index(op.f('ix_entities_article_id'), table_name='entities')
    op.drop_index('idx_entities_text_type', table_name='entities')
    op.drop_index('idx_entities_created_at', table_name='entities')
    op.drop_index('idx_entities_article_type', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
